version: "3.7"

services:

  mpp_backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    # command: mvnw package && java -jar target/mpp-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080