version: "3.7"

services:

  mpp_backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
#     command: mvnw package && java -jar target/mpp-0.0.1-SNAPSHOT.jar
    ports:
      - 8080:8080

  # db:
  #   image: mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 27107:27107